#!/usr/bin/env bash
#
# End-to-end demo for phantom-finance.
#
# Runs the full pipeline against the bundled bilingual (zh + en) CSV fixtures:
#   import (bank_en.csv + bank_zh.csv) -> budget set/show -> monthly report
#
# Everything is sandboxed under a temp dir via PHANTOM_*_HOME env vars, so this
# never touches your real ~/.phantom-mesh/. The data is the synthetic fixtures
# in tests/fixtures/ (no real accounts, no real money).
#
# Usage:
#   ./examples/demo.sh            # run the demo, print the report
#   ./examples/demo.sh --save     # also copy the report to docs/sample-month-report.md
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FIXTURES="$REPO_ROOT/tests/fixtures"
MONTH="2026-06"

# Sandbox: an isolated phantom-mesh home that we clean up on exit.
SANDBOX="$(mktemp -d)"
trap 'rm -rf "$SANDBOX"' EXIT
export PHANTOM_MESH_HOME="$SANDBOX/mesh"
export PHANTOM_FINANCE_HOME="$SANDBOX/finance"

# Use the installed console script if present, else fall back to the module.
if command -v phantom-finance >/dev/null 2>&1; then
  pf() { phantom-finance "$@"; }
else
  pf() { python3 -m phantom_finance.cli "$@"; }
fi

echo "== phantom-finance demo =="
echo "sandbox home: $SANDBOX"
echo

echo "-- 1. import English bank CSV (auto-detects Date/Amount/Description) --"
pf import "$FIXTURES/bank_en.csv" --account cathay-en
echo

echo "-- 2. import 中文 bank CSV (BOM + 交易日期/金額/摘要 + 2026/6/1 dates) --"
pf import "$FIXTURES/bank_zh.csv" --account cathay-zh
echo

echo "-- 3. set a couple of monthly budgets --"
pf budget set dining 5000
pf budget set housing 30000
echo

echo "-- 4. budget status for $MONTH --"
pf budget show --month "$MONTH"
echo

echo "-- 5. write the monthly report --"
REPORT_PATH="$PHANTOM_MESH_HOME/logs/phantom-finance/$MONTH-report.md"
pf report --month "$MONTH"
echo

echo "-- generated report ($REPORT_PATH) --"
echo
cat "$REPORT_PATH"

if [[ "${1:-}" == "--save" ]]; then
  DEST="$REPO_ROOT/docs/sample-month-report.md"
  {
    echo "<!-- Generated by examples/demo.sh from the synthetic fixtures in"
    echo "     tests/fixtures/ (bank_en.csv + bank_zh.csv). Do not edit by hand;"
    echo "     re-run: ./examples/demo.sh --save -->"
    echo
    cat "$REPORT_PATH"
  } > "$DEST"
  echo
  echo "saved sample report -> $DEST"
fi
